language: php
php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot
  - master

matrix:
  allow_failures:
    - php: master

before_script:
  - composer self-update
  - composer update --no-interaction

script:
  - vendor/bin/phing
